version: '3'
services:
  client:
    build: ./client
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - webnet

  server:
    build: ./server
    environment:
      NODE_ENV: production
      SERVER_URL: 'localhost'
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

networks:
  webnet:
