type Game {
  id: ID!
  fen: String!
  legalMoves: [Move!]!
  moveHistory: [String!]!
  gameStatus: GameStatus!
  playerInfo: PlayerInfo!
  keySquares: KeySquares!
}

type GameStatus {
  isFinished: Boolean!
  statusText: String!
}

type PlayerInfo {
  myTurn: Boolean!
  isWhite: Boolean!
}

type KeySquares {
  checkSquare: String
  lastMove: [String!]
}

type Query {
  createGame: Game!
  getGame(id: ID!): Game
}

type Mutation {
  makeMove(id: ID!, from: String!, to: String!, promoteTo: String): Boolean!
}
