type Game {
  id: ID!
  fen: String!
  startTime: String!
  increment: String!
  status: String!
  legalMoves: [Move!]!
  moveHistory: [String!]!
  gameStatus: GameStatus!
  playerInfo: PlayerInfo!
  keySquares: KeySquares!
}

type GameStatus {
  isFinished: Boolean!
  statusText: String!
  drawOffered: String
}

type PlayerInfo {
  myTurn: Boolean!
  myColour: String
  whiteTimeLeft: String!
  blackTimeLeft: String!
}

type KeySquares {
  checkSquare: String
  lastMove: [String!]
}

type Query {
  getGame(id: ID!): Game
  getGameCount: Int!
  myGames: [Game!]!
  openGames: [Game!]!
}

type Mutation {
  createGame(startTime: Int!, increment: Int!, colour: String!): String!
  joinGame(id: ID!): Boolean!
  offerDraw(id: ID!): Boolean!
  acceptDraw(id: ID!): Boolean!
  resign(id: ID!): Boolean!
}

type Subscription {
  gameCountUpdated: Int!
  gameUpdated(id: ID!): Game!
  myGamesUpdated: [Game!]
  openGamesUpdated: [Game!]
}
